services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USER=${MINIO_ROOT_USER}
      - MINIO_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      - postgres
      - minio
    networks:
      - nusantara-network
  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nusantara-network
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    volumes:
      - miniodata:/data
    networks:
      - nusantara-network
volumes:
  pgdata:
  miniodata:
networks:
  nusantara-network:
    driver: bridge
